---
- name: Config Elk VM w/docker
  hosts: ELK
  remote_user: azuser
  become: true
  tasks:
    # Use apt module installs
    - name: Install Packeges, Docker, Python3
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

    - name: Install Python3-pip
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

     # Use pip module (it will default to pip3)
    - name: install docker module
      pip:
        name: docker
        state: present

     # Use systcl module
    - name: Use more memory always on
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present
        reload: yes

    # Use docker_container module  
    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        # Please list the ports that ELK runs on
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

      # Use systemd module
    - name: Enable service docker on boot
      systemd:
        name: docker
        enabled: yes
